codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        branches:
          - main
          - master
        if_ci_failed: error
        only_pulls: false
    
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        branches:
          - main
          - master
        if_ci_failed: error
        only_pulls: false

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "venv/"
  - "env/"
  - "ENV/"
  - ".venv/"
  - "__pycache__/"
  - "*.pyc"
  - ".pytest_cache/"
  - ".coverage"
  - "htmlcov/"
  - ".tox/"
  - ".hypothesis/"
  - ".mypy_cache/"
  - ".git/"
  - ".github/"
  - "*.md"
  - ".gitignore"
  - ".gitattributes"
  - "codecov.yml"
  - "requirements.txt"

github_checks:
  annotations: true

